### ISSUE TITLE
os.chdir DOESN'T work on Windows - Error 123

### ISSUE THREAD

**Issue by VitorAugusto** [simon-v/minipos#1]
```
D:\Python - maquina virtual POS\minipos>python minipos
Traceback (most recent call last):
  File "minipos", line 20, in <module>
    os.chdir(os.path.dirname(__file__))
WindowsError: [Error 123] A sintaxe do nome do arquivo, do nome do diret¾rio ou do r¾tulo do volume estß incorreta: ''
```

**Comment by VitorAugusto** [comment]
Easily fixed replacing to 
`os.getcwd()
`
I have not tried it on linux yet, but on both platforms that same command should work.

**Comment by simon-v** [comment]
https://docs.python.org/2/library/os.html#os.chdir
`Availability: Unix, Windows.`

This has to be something else. Unfortunately, i don't have a Windows installation to test on.

I have a hunch, but i'm pretty sure i'm wrong. Could you check to see what does the `__file__` resolve to on your system (e.g., by inserting a `print(__file__)` call right before the crash?

P.S.: `os.getcwd()` does not do what is supposed to happen in this line (change the working directory to the script's directory).
